login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.login_auth, 
        name='form'),
    url(r'^logout/$', views.logout_auth, 
        name='out'),
    url(r'^attempts/$', views.login_attempts, 
        name='attempts'),
    url(r'^logs/$', views.login_logs, 
        name='logs'),
    url(r'^attempts/delete$', views.delete_old_attempts, 
        name='attempts_delete'),
]

app_name = 'login'

timeplanner/urls.py
from django.contrib import admin
from django.urls import path, include

# from freports.admin import admin_site
from business_card import views as business_card

urlpatterns = [
    path('', business_card.first_page, name='first_page'),
    path('freports/', include('freports.urls', namespace='freports')),
    path('login/', include('login.urls', namespace='login')),
    path('finance/', include('finance.urls', namespace='finance')),
    path('admin/', admin.site.urls),

]

login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, signals
from django.contrib.auth.decorators import (
    login_required, 
    permission_required
    )
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone

from axes.models import AccessAttempt, AccessLog

def login_auth(request):
    attempts = AccessAttempt.objects.all()
    login_attempts_last = 0
    if attempts:
        login_attempts_last = attempts[0].failures_since_start

    if login_attempts_last > 3:
        messages.error(request, 
            "Кількість спроб перевищила допустиму, спробуйте пізніше")
        return render(request, 'login/form_locked.html', {})

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        try:
            user = authenticate(request, username=username, 
                password=password)
        
            if user is not None:
                login(request, user)
                messages.success(request, 
                    "Ви успішно увійшли як %s" % username)
                return HttpResponseRedirect(
                    reverse('freports:reports_list'))
            else:
                messages.error(request, 
                    u"Невірно введене ім'я користувача або пароль")
                login_attempts_last += 1
        except UnicodeEncodeError:
            messages.error(request,
                u"Некоректно введене ім'я користувача або пароль")
            login_attempts_last += 1

    return render(request, 'login/form.html', {})

def logout_auth(request):
    logs = AccessLog.objects.all()
    logs.last().logout_time = timezone.now()
    logout(request)
    return HttpResponseRedirect(reverse('login:form'))

@login_required(login_url='/login/')
@permission_required('admins', raise_exception=True)
def login_attempts(request):
    attempts_all = AccessAttempt.objects.all()
    attempts = attempts_all
    for attempt in attempts:
        attempt.new_post_data = attempt.post_data.split('---------')
    return render(request, 'login/attempts.html', 
        {'attempts': attempts})

@login_required(login_url='/login/')
@permission_required('admins', raise_exception=True)
def login_logs(request):
    logs = AccessLog.objects.all().order_by('attempt_time').reverse()
    if request.GET.get('all_pages', '') == '':
        paginator = Paginator(logs, 8)
        page = request.GET.get('page', '')
        try:
            logs = paginator.page(page)
        except PageNotAnInteger:
            logs = paginator.page(1)
        except EmptyPage:
            logs = paginator.page(paginator.num_page)
    return render(request, 'login/logs.html', 
        {'logs': logs})

@login_required(login_url='/login/')
@permission_required('admins', raise_exception=True)
def delete_old_attempts(request):
    attempts = AccessAttempt.objects.all()
    old_logs = 0
    for attempt in attempts:
        substract = timezone.now().date() - attempt.attempt_time.date()
        if substract.days > 31:
            attempt.delete()
            old_logs += 1
    if old_logs > 0:
        messages.success(request, 
            u"Логи, записані більше місяця тому, успішно видалено")
    else:
        messages.warning(request,
            u"Давніх спроб входу не виявлено")
    return HttpResponseRedirect(reverse('login:attempts'))

login/templates/login/attempts.html
{% extends "freports/base.html" %}

{% block title %}

<div class="col">
    <span class="h1">Записи невдалих спроб входу</span>
</div>

{% endblock title %}

{% block content %}

<a class="btn btn-outline-info mb-3" href="{% url 'login:logs' %}">Показати усі логування</a>

{% if attempts %}
<table class="table table-hover table-responsive-lg">
    <thead class="thead-light">
        <tr>
            <th>Використане ім'я користувача</th>
            <th>Час останньої спроби</th>
            <th>Кількість невдалих спроб</th>
            <th>IP адреса</th>
            <th>Детальні дані</th>
        </tr>
    </thead>

    <tbody>
        {% for attempt in attempts %}
        <tr>
            <td>{{ attempt.username }}</td>
            <td>{{ attempt.attempt_time }}</td>
            <td>{{ attempt.failures_since_start }}</td>
            <td>{{ attempt.ip_address }}</td>
            <td>
                <a class="btn btn-info" data-toggle="collapse" href="#collapse{{ attempt.id }}" role="button" aria-expanded="false" aria-controls="collapse{{ attempt.id }}">
                Дивитись
                </a>
            </td>
        </tr>
        <tr class="collapse" id="collapse{{ attempt.id }}">
            <td colspan="5">
                <p>Браузер користувача - {{ attempt.user_agent }}</p>
                <ul>Спроби входу: 
                    {% for row in attempt.new_post_data %}
                    <li>{{ row }}</li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
        {% endfor %}  
    </tbody>
</table>

<a class="btn btn-outline-danger mt-2" href="{% url 'login:attempts_delete' %}">Видалити давні спроби входу</a>


{% else %}
<p>На цей момент дані відсутні</p>
{% endif %}

{% endblock content %}

login/templates/login/form.html
{% extends "freports/base.html" %}

{% block title %}

<div class="col-5"></div>
<div class="col-4">
    <h2 id="questionsHeader">Вхід для адміністратора</h2>
</div>
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-3"></div>
    <form class="form-horizontal col-sm-6" action="" method="post" enctype="multipart/form-data" role="form">
        {% csrf_token %}
        <div class="form-group row">
            <label for="inputUsername" class="col-sm-4 col-form-label">Ім'я користувача</label>
            <div class="col-sm-8">
                <input type="text" class="form-control {% if errors %}is-valid{% endif %}" autocomplete="off"
                    id="inputUsername" name="username" placeholder="Введіть ім'я користувача" required />
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-4 col-form-label">Пароль</label>
            <div class="col-sm-8">
                <input type="password" class="form-control {% if errors %}is-valid{% endif %}" autocomplete="off"
                    id="inputPassword" name="password" placeholder="Введіть пароль" required />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4"></div>
            <div class="col-sm-6">
              <input type="submit" class="btn btn-primary" value="Увійти"
                     name="save_button" />
              <a class="btn btn-link" href="{% url 'first_page' %}">Повернутись на головну</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

login/templates/login/form_locked.html
{% extends "freports/base.html" %}

{% block title %}

<div class="col-5"></div>
<div class="col-4">
    <h2 id="questionsHeader">Вхід для адміністратора</h2>
</div>
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-3"></div>
    <form class="form-horizontal col-sm-6" action="" method="post" enctype="multipart/form-data" role="form">
        {% csrf_token %}
        <div class="form-group row">
            <div class="col-sm-4"></div>
            <div class="col-sm-6">
              <a class="btn btn-link" href="{% url 'first_page' %}">Повернутись на головну</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

login/templates/login/logs.html
{% extends "freports/base.html" %}

{% block title %}

<div class="col">
    <span class="h1">Записи входів</span>
</div>

{% endblock title %}

{% block content %}

<a class="btn btn-outline-warning mb-3" href="{% url 'login:attempts' %}">Показати невдалі спроби</a>
{% if logs %}
<table class="table table-hover table-responsive-lg">
    <thead class="thead-light">
        <tr>
            <th>Використане ім'я користувача</th>
            <th>Час входу</th>
            <th>Час виходу</th>
            <th>IP адреса</th>
            <th>Детальні дані</th>
        </tr>
    </thead>

    <tbody>
        {% for log in logs %}
        <tr>
            <td>{{ log.username }}</td>
            <td>{{ log.attempt_time }}</td>
            <td>{% if log.logout_time %} {{ log.logout_time }}{% endif %}</td>
            <td>{{ log.ip_address }}</td>
            <td>
                <a class="btn btn-info" data-toggle="collapse" href="#collapse{{ log.id }}" role="button" aria-expanded="false" aria-controls="collapse{{ log.id }}">
                Дивитись
                </a>
            </td>
        </tr>
        <tr class="collapse" id="collapse{{ log.id }}">
            <td colspan="5">
                <p>Браузер користувача - {{ log.user_agent }}</p>
                <p>Адреса запиту - {{ log.path_info }}</p>
                <p>Інші дані - {{ log.http_accept }}</p>

            </td>
        </tr>
        {% endfor %}  
    </tbody>
</table>

{% if logs.has_other_pages %}
{% include "freports/pagination.html" with items=logs url_next="login:logs" %}
{% endif %}

{% else %}
<p>На цей момент дані відсутні</p>
{% endif %}

{% endblock content %}