finance/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import permission_required

from . import views
from .views import (
    AccountList,
    AccountDetail,
    OrderDetail,
    IncomeList,
    IncomeCreate, 
    IncomeEdit, 
    IncomeDelete,
    ExecutionList,
    ExecutionCreate,
    ExecutionEdit,
    ExecutionDelete,
    )

urlpatterns = [
    # account URLs
    url(r'^accounts/$', 
        permission_required('admins')(AccountList.as_view()), 
        name='accounts_list'), 
    url(r'^account/(?P<pk>\d+)/detail/$', 
        permission_required('admins')(AccountDetail.as_view()),
        name='detail_account'),
    url(r'^accounts/add/$', views.add_account, 
        name='add_account'),
    url(r'^accounts/(?P<aid>\d+)/edit/$', views.edit_account,
        name='edit_account'),
    url(r'^accounts/(?P<aid>\d+)/delete/$', views.delete_account,
        name='delete_account'),

    # order URLs
    url(r'^orders/$', views.orders_list, 
        name='orders_list'),
    url(r'^orders/(?P<pk>\d+)/detail/$', 
        permission_required('admins')(OrderDetail.as_view()),
        name='detail_order'),   
    url(r'^orders/add/$', views.add_order,
        name='add_order'),
    url(r'^orders/(?P<oid>\d+)/edit/$', views.edit_order,
        name='edit_order'),
    url(r'^orders/(?P<oid>\d+)/delete/$', views.delete_order,
        name='delete_order'),

    # income URLs
    url(r'^incomes/$', 
        permission_required('admins')(IncomeList.as_view()), 
        name="incomes_list"),
    url(r'^incomes/add/$', 
        permission_required('admins')(IncomeCreate.as_view()),
        name="add_income"),
    url(r'^incomes/(?P<pk>\d+)/edit/$', 
        permission_required('admins')(IncomeEdit.as_view()),
        name="edit_income"),
    url(r'^incomes/(?P<pk>\d+)/delete/$', 
        permission_required('admins')(IncomeDelete.as_view()),
        name="delete_income"),

    # execution URLs
    url(r'^executions/$', 
        permission_required('admins')(ExecutionList.as_view()), 
        name='executions_list'),
    url(r'^executions/add/$', 
        permission_required('admins')(ExecutionCreate.as_view()),
        name="add_execution"),
    url(r'^executions/(?P<pk>\d+)/edit/$', 
        permission_required('admins')(ExecutionEdit.as_view()),
        name="edit_execution"),
    url(r'^executions/(?P<pk>\d+)/delete/$', 
        permission_required('admins')(ExecutionDelete.as_view()),
        name="delete_execution"),
]

app_name = 'finance'

freports/api/urls.py
from django.conf.urls import url

from .views import (
    ReportListApiView, 
    ReportDetailApiView,
    ReportCreateAwardApiView
    )

urlpatterns = [
    # report urls
    url(r'^$', ReportListApiView.as_view(), 
        name='reports_list'),
    url(r'^(?P<pk>\d+)/$', ReportDetailApiView.as_view(),
        name='report_detail'),
    url(r'^create/$', ReportCreateAwardApiView.as_view(), 
        name='report_create')
]

freports/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views
from .views import (
    ResearchListView,
    ResearchDetailView, 
    ResearchCreate, 
    ResearchEdit,
    ResearchDelete
    )

urlpatterns = [
    # report urls
    url(r'^$', views.reports_list, 
        name='reports_list'),
    url(r'^add/new_report/$', views.add_new_report, 
        name='add_new_report'),
    url(r'^(?P<rid>\d+)/edit/$', views.report_edit, 
        name='report_edit'),
    url(r'^(?P<rid>\d+)/delete/$', views.delete_report, 
        name='delete_report'),
    url(r'^update_info/$', views.update_info, 
        name='reports_update'),

    # research urls
    url(r'^researches/$', ResearchListView.as_view(), 
        name='researches_list'),
    url(r'^researches/(?P<pk>\d+)/$', ResearchDetailView.as_view(), 
        name='research_detail'),
    url(r'^add/new_research/$', views.add_new_research, 
        name='add_new_research'),
    url(r'^researches/add/$', ResearchCreate.as_view(), 
        name="add_research"),
    url(r'^researches/(?P<pk>\d+)/edit/$', ResearchEdit.as_view(), 
        name='edit_research'),
    url(r'^researches/(?P<pk>\d+)/delete/$', ResearchDelete.as_view(), 
        name='delete_research'),

    # event urls
    url(r'^(?P<rid>\d+)/details/$', views.details_list, 
        name='report_detail'),
    url(r'^(?P<rid>\d+)/details/order/add/$', views.add_order, 
        name='add_order'),
    url(r'^(?P<rid>\d+)/details/add/(?P<kind>\w+)/$', 
        views.add_detail, name='add_detail'),
    url(r'^(?P<rid>\d+)/details/(?P<did>\d+)/edit/$', 
        views.edit_detail, name='edit_detail'),
    url(r'^(?P<rid>\d+)/details/(?P<did>\d+)/delete/$', 
        views.delete_detail, name='delete_detail'),
    url(r'^(?P<rid>\d+)/details/schedule/add/$',
        views.add_schedule, name='add_schedule'),
    url(r'^(?P<rid>\d+)/details/bill/add/$',
        views.add_bill, name='add_bill'),

    # participant urls
    url(r'^partisipants/$', views.participants_list, 
        name='participants_list'),
    url(r'^partisipants/(?P<rid>\d+)/detail/$', 
        views.participant_detail, name='participant_detail'),
    url(r'^(?P<rid>\d+)/partisipants/add/(?P<status>\w+)/$', 
        views.add_participant, name='add_participant'),
    url(r'^(?P<rid>\d+)/partisipants/(?P<did>\d+)/edit/$', 
        views.edit_participant, name='edit_participant'),
    url(r'^(?P<rid>\d+)/partisipants/(?P<did>\d+)/delete/$', 
        views.delete_participant, name='delete_participant'),

    # subject urls
    url(r'^subjects/$', views.subjects_list, 
        name='subjects_list'),
    url(r'^subjects/(?P<sid>\d+)/detail/$', views.subject_detail, 
        name='subject_detail'),
    url(r'^(?P<rid>\d+)/subjects/add/$', views.add_subject, 
        name='add_subject'),
    url(r'^(?P<rid>\d+)/subjects/(?P<sid>\d+)/edit/$', 
        views.edit_subject, name='edit_subject'),
    url(r'^(?P<rid>\d+)/subjects/(?P<sid>\d+)/delete/$', 
        views.delete_subject, name='delete_subject'),

    # contact urls
    url(r'^contacts/$', views.contacts_list, name='contacts_list'),
    url(r'^contacts/update/$', views.update_contacts_status, 
        name='contacts_update_status'),
    url(r'^contacts/(?P<cid>\d+)/detail/$', views.contact_detail, 
        name="contact_detail"),
    url(r'^contacts/add/$', views.add_contact, 
        name="add_contact"),
    url(r'^contacts/(?P<cid>\d+)/edit/$', views.edit_contact, 
        name="edit_contact"),
    url(r'^contacts/(?P<cid>\d+)/delete/$', views.delete_contact, 
        name="delete_contact"),

    # court urls
    url(r'^courts/$', views.courts_list, name='courts_list'),
    url(r'^courts/(?P<cid>\d+)/detail/$', views.court_detail, 
        name='court_detail'),
    url(r'^courts/add/$', views.add_court, 
        name='add_court'),
    url(r'^courts/(?P<cid>\d+)/edit/$', views.edit_court, 
        name='edit_court'),
    url(r'^courts/(?P<cid>\d+)/delete/$', views.delete_court, 
        name='delete_court'),

    # judge urls
    url(r'^judges/$', views.judges_list, name='judges_list'),
    url(r'^judges/(?P<jid>\d+)/detail/$', views.judge_detail, 
        name='judge_detail'),
    url(r'^judges/add/$', views.add_judge, 
        name='add_judge'),
    url(r'^judges/(?P<jid>\d+)/edit/$', views.edit_judge, 
        name='edit_judge'),
    url(r'^judges/(?P<jid>\d+)/delete/$', views.delete_judge, 
        name='delete_judge'),

    # task urls
    url(r'^tasks/$', views.tasks_list, name='tasks_list'),
    url(r'^tasks/change_status$', views.change_status_task, 
        name='change_status_task'),
    url(r'^tasks/today/$', views.tasks_today_list, 
        name='tasks_today_list'),
    url(r'^tasks/add/$', views.add_task, name='add_task'),
    url(r'^tasks/(?P<tid>\d+)/edit/$', views.edit_task, 
        name='edit_task'),
    url(r'^tasks/(?P<tid>\d+)/delete/$', views.delete_task, 
        name='delete_task'),
    url(r'^tasks/delete_old/$', views.delete_old_tasks, 
        name='delete_old_tasks'),
]

app_name = 'freports'

login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.login_auth, 
        name='form'),
    url(r'^logout/$', views.logout_auth, 
        name='out'),
    url(r'^attempts/$', views.login_attempts, 
        name='attempts'),
    url(r'^logs/$', views.login_logs, 
        name='logs'),
    url(r'^attempts/delete$', views.delete_old_attempts, 
        name='attempts_delete'),
]

app_name = 'login'

timeplanner/urls.py
from django.contrib import admin
from django.urls import path, include

# from freports.admin import admin_site
from business_card import views as business_card

urlpatterns = [
    path('', business_card.first_page, name='first_page'),
    path('freports/', include('freports.urls', namespace='freports')),
    path('login/', include('login.urls', namespace='login')),
    path('finance/', include('finance.urls', namespace='finance')),
    path('admin/', admin.site.urls),

]

login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

freports/api/views.py
from rest_framework.filters import OrderingFilter
from rest_framework.generics import (
    ListAPIView, 
    RetrieveAPIView,
    CreateAPIView,
    )
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView

from .serializers import (
    ReportListSerializer, 
    ReportDetailSerializer,
    ReportCreateAwardSerializer
    )
from ..models import Report

class ReportListApiView(ListAPIView):
    serializer_class = ReportListSerializer
    permission_classes = (IsAuthenticated,)
    queryset = Report.objects.all()
    filter_backends = (OrderingFilter,)
    ordering_fields = ('number', 'address')
    ordering = ('number',)

class ReportDetailApiView(RetrieveAPIView):
    serializer_class = ReportDetailSerializer
    permission_classes = (IsAuthenticated,)
    queryset = Report.objects.all()

class ReportCreateAwardApiView(CreateAPIView):
    queryset = Report.objects.all()
    serializer_class = ReportCreateAwardSerializer
    permission_classes = (IsAuthenticated,)

    def perform_create(self, serializer):
        serializer.save(
            plaintiff='-',
            defendant='-',
            address='-',
            object_name='-',
            research_kind='-',
            active=None
        )

freports/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from itertools import chain
from datetime import date

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

from .models import ForensicReport

def reports_list(request):
    if request.GET.get('executed'):
        reports = ForensicReport.objects.all().order_by('number').filter(executed=True)
    else:
        reports = ForensicReport.objects.all().order_by('number').filter(executed=False)
    order_by = request.GET.get('order_by')
    reverse = request.GET.get('reverse')
    if order_by:
        reports = reports.order_by(order_by)
        if reverse:
            reports = reports.reverse()
    else:
        reports_top = reports.filter(active=True)
        reports_low = reports.filter(active=False)
        reports = list(chain(reports_top, reports_low))
    for report in reports:
        if request.GET.get('executed'):
            days_amount = report.date_executed - report.date_arrived
            report.days_amount = days_amount.days
        else:
            days_amount = date.today() - report.date_arrived
            report.days_amount = days_amount.days
    return render(request, 'freports/reports_list.html', {'reports': reports})

def add_report(request):
    header = u'Додавання провадження'

    if request.method == 'POST':
        if request.POST.get('save_button'):
            validate_data = valid_report(request.POST)
            errors = validate_data['errors']
            new_report = validate_data['data_report']

            if errors:
                messages.error(request, "Виправте наступні недоліки")
                return render(request, 'freports/add_report.html', {'header': header, 'errors': errors,
                    'content': new_report})

            else:
                new_report = ForensicReport(**new_report)
                new_report.save()
                messages.success(request, "Провадження №%s/017 успішно додане" % new_report.number)

        elif request.POST.get('cancel_button'):
            messages.warning(request, "Додавання провадження скасовано")

        return HttpResponseRedirect(reverse('forensic_reports_list'))

    else:
        return render(request, 'freports/add_report.html', {'header': header})


def edit_report(request, rid):
    header = 'Редагування провадження'
    content = ForensicReport.objects.get(pk=rid)

    if request.method == 'POST':
        if request.POST.get('save_button'):
            current_report = content

            validate_data = valid_report(request.POST)
            errors = validate_data['errors']
            new_report = validate_data['data_report']

            if errors:
                messages.error(request, "Виправте наступні недоліки")
                return render(request, 'freports/add_report.html', {'header': header, 'content': new_report,
                    'errors': errors})

            else:
                current_report.number = new_report['number']
                current_report.address = new_report['address']
                current_report.plaintiff = new_report['plaintiff']
                current_report.defendant = new_report['defendant']
                current_report.object_name = new_report['object_name']
                current_report.research_kind = new_report['research_kind']
                current_report.active = new_report['active']
                current_report.date_arrived = new_report['date_arrived']
                current_report.executed = new_report['executed']
                try:
                    current_report.date_executed = new_report['date_executed']
                except KeyError:
                    pass
                current_report.save()
                messages.success(request, "Провадження №%s/017 успішно відкориговане" % current_report.number)

        elif request.POST.get('cancel_button'):
            messages.warning(request, "Редагування провадження скасовано")

        return HttpResponseRedirect(reverse('forensic_reports_list'))

    else:
        content.date_arrived = content.date_arrived.isoformat()
        if content.executed:
            content.date_executed = content.date_executed.isoformat()
        return render(request, 'freports/add_report.html', {'header': header, 'content': content})


def delete_report(request, rid):
    if request.method == 'GET':
        report = ForensicReport.objects.get(pk=rid)
        return render(request, 'freports/delete_report.html', {'report': report})
    elif request.method == 'POST':
        if request.POST.get('delete_button'):
            current_report = ForensicReport.objects.get(pk=rid)
            current_report.delete()
            messages.success(request, "Провадження №%s/017 успішно видалено" % current_report.number)
        elif request.POST.get('cancel_button'):
            messages.warning(request, "Видалення провадження скасовано")

        return HttpResponseRedirect(reverse('forensic_reports_list'))

def valid_report(data_post):
    errors = {}
    new_report = {}

    date_arrived = data_post.get('date_arrived')
    if not date_arrived:
        errors['date_arrived'] = u"Дата надходження є обов'язковою"
    else:
        try:
            new_report['date_arrived'] = date_arrived
        except ValueError:
            errors['date_arrived'] = u"Введіть коректний формат дати"

    report_number = data_post.get('number')
    if not report_number:
        errors['number'] = u"Номер висновку є обов'язковим"
    else:
        try:
            new_report['number'] = int(report_number)
        except ValueError:
            new_report['number'] = report_number
            errors['number'] = u"Будь-ласка введіть число"

    address = data_post.get('address')
    if not address:
        errors['address'] = u"Адреса об'єкту є обов'язковою"
    else:
        new_report['address'] = address

    plaintiff = data_post.get('plaintiff')
    if not plaintiff:
        errors['plaintiff'] = u"Прізвище позивача є обов'язковим"
    else:
        new_report['plaintiff'] = plaintiff

    defendant = data_post.get('defendant')
    if not defendant:
        errors['defendant'] = u"Прізвище відповідача є обов'язковим"
    else:
        new_report['defendant'] = defendant

    object_name = data_post.get('object_name')
    if not object_name:
        errors['object_name'] = u"Тип об'єкту є обов'язковим"
    else:
        new_report['object_name'] = object_name

    research_kind = data_post.get('research_kind')
    if not research_kind:
        errors['research_kind'] = u"Вид дослідження є обов'язковим"
    else:
        new_report['research_kind'] = research_kind

    active = data_post.get('active')
    if active:
        if active == 'executed':
            new_report['active'] = False
            new_report['executed'] = True
        else:
            new_report['active'] = active
            new_report['executed'] = False

    date_executed = data_post.get('date_executed')
    if date_executed:
        new_report['date_executed'] = data_post.get('date_executed')

    return {'errors': errors, 'data_report': new_report}

freports/templates/freports/base.html
{% load static %}

<!DOCTYPE html>

<html lang="uk">
    <head>
        <meta charset="UTF-8" />
        <title>BudExpert</title>
        <link rel="shortcut icon" href="{{ PORTAL_URL }}{% static 'apple-icon-60x60.png' %}" type="image/x-icon">

        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700|Nunito:400,700" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" 
            href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0/css/tempusdominus-bootstrap-4.min.css" />
        <link rel="stylesheet" href="{{ PORTAL_URL }}{% static 'css/main.css' %}" type="text/css">
        <link rel="stylesheet" href="{{ PORTAL_URL }}{% static 'css/sidebar.css' %}" type="text/css">
    </head>

    <body>
        {% if user.is_authenticated %}
        <!-- Main Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'freports:reports_list' %}">Time Planner</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" 
                aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {% url "freports:reports_list" as url_reports %}
                    {% url "freports:researches_list" as url_researches %}
                    {% url "freports:participants_list" as url_participants %}
                    {% url "freports:subjects_list" as url_subjects  %}
                    {% url "freports:contacts_list" as url_contacts %}
                    {% url "freports:judges_list" as url_judges %}
                    {% url "freports:courts_list" as url_courts %} 
                    {% url "freports:tasks_list" as url_tasks %} 
                    {% url "finance:orders_list" as url_orders %}
                    {% url "finance:accounts_list" as url_accounts %} 
                    {% url "finance:incomes_list" as url_incomes %}
                    {% url "finance:executions_list" as url_executions %}
                    <ul class="navbar-nav mr-auto">
                        {% if perms.admins %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == url_reports or request.path == url_participants or request.path == url_subjects or request.path == url_researches %}active{% endif %}"
                                href="{{ url_reports }}">Провадження</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == url_contacts %}active{% endif %}"
                                href="{{ url_contacts }}">Контакти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == url_courts or request.path == url_judges %}active{% endif %}"
                                href="{{ url_courts }}">Суди</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == url_tasks %}active{% endif %}"
                                href="{{ url_tasks }}">Завдання</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == url_orders or request.path == url_accounts or request.path == url_incomes or request.path == url_executions %}active{% endif %}"
                                href="{{ url_orders }}">Фінанси</a>
                        </li>
                        {% endif %}
                    </ul>
                    <div class="btn-group" role="group">
                        {% if TODAY_TASKS == True and perms.admins %}
                        <button id="btnGroupDrop1" type="button" class="btn btn-danger" href="{% url 'freports:tasks_today_list' %}"
                            aria-haspopup="true" aria-expanded="false">Сьогодні</button>
                        {% else %}
                        <button type="button" class="btn" aria-haspopup="true" aria-expanded="false">
                            {{ request.user.username }}
                        </button>
                        {% endif %}
                        <button type="button" class="btn dropdown-toggle dropdown-toggle-split"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        </button>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                            {% if perms.admins %}
                            <a class="dropdown-item" href="{% url 'freports:reports_update' %}">Оновлення даних</a>
                            <a class="dropdown-item" href="{% url 'login:attempts' %}">Записи логування</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'login:out' %}">Вийти</a>
                        </div>
                    </div>
                </div>
            </div>
         <!-- Navbar content -->
        </nav>

        {% endif %}

        <div class="wrapper">
            <!-- Sidebar -->
            {% if perms.admins %}
            {% block sidebar %}{% endblock sidebar %}
{% if request.path == url_reports or request.path == url_participants or request.path == url_subjects or request.path == url_judges or request.path == url_courts or request.path == url_orders or request.path == url_accounts or request.path == url_incomes or request.path == url_researches or request.path == url_executions %}
                <div class="row">
                    <div class="col">
                        <button type="button" id="sidebarCollapse" class="navbar-btn {% if request.COOKIES.sidebar == 'active' %}active{% endif %}">
                            <span></span>
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
                {% endif %}
                {% endif %}
            <!-- Page Content -->
            <div id="content" class="container">
                
                <div class="row" id="second-header">
                    {% block title %}{% endblock title %}
                </div>

                <div class="row" id="message">
                    <div class="col">
                        {% block messages %}
                            {% if messages %}
                            {% for message in messages %}
                            <div class="alert alert-{% if message.tags == 'error' %}danger
                                 {% else %}{{ message.tags }}{% endif %}
                                 "
                                 role="alert">{{ message }}</div>
                            {% endfor %}
                            {% endif %}
                        {% endblock messages %}
                        {% block extra_messages %}
                        {% endblock extra_messages %}
                    </div>
                </div>

                <div class="row" id="main-content">
                    <div class="col-12">
                        {% block content %}{% endblock content %}
                    </div>
                </div>
                <div class="row" id="extra-content">
                    <div class="col-12">
                        {% block extra_content %}{% endblock extra_content %}
                    </div>
                </div>

                <div class="row" id="footer">
                    <div class="col-12">
                        <hr />
                        <p>{% if user.is_authenticated and perms.admins %}Time Planner, version 2.1.0, 2017-2021 &copy; <a href="{% url 'admin:index' %}">Адмінка</a>{% endif %}</p>
                    </div>
                </div>
            </div>

        </div> 

        <!-- Start Modal -->
        <div class="modal fade" tabindex="-1" role="dialog" id="modalForm">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content" >
                    <div class="modal-header" id="first-header">
                        <div class="text-center"></div>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <!-- -->
                    </div>
                    <div class="modal-body">
                        <!-- -->
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <!-- End Modal -->

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="http://malsup.github.io/jquery.form.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
        <script type="text/javascript" 
            src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0/js/tempusdominus-bootstrap-4.min.js">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/uk.js"></script>
        <script src="{{ PORTAL_URL }}{% static 'js/main.js' %}" type="text/javascript"></script>
    </body>


</html>

freports/templates/freports/research_detail.html
{% extends "freports/base.html" %}
{% load get_item %}

{% block title %}
    <div class="col-3">
        <a type="button" class="btn btn-outline-dark mb-3"
            href="{% url 'freports:researches_list' %}">Повернутись до списку досліджень</a>
    </div>
    <div class="col-9">
        <h2 id="report-detail-header">Детальна інформація про експертне дослідження №{{ object.full_number }}</h2>
    </div>

{% endblock title %}

{% block content %}

<div class="row" id="main-participants">
    <div class="col-sm-12">

        <table class="table table-sm table-lg-responsive table-hover">
            <tbody>
                <tr>
                    <th scope="row">Заявник</th>
                    <td>
                        {{ object.applicant }}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Адреса</th>
                    <td>
                        {{ object.address }}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Об'єкт дослідження</th>
                    <td>
                        {{ object.object_name }}
                    </td>
                </tr>
                {% if object.cost %}
                <tr>
                    <th scope="row">Вартість</th>
                    <td>{{ object.cost }}грн</td>
                </tr>
                {% endif %}

                {% if object.addition_info %}
                <tr>
                    <th scope="row">Додаткова інформація</th>
                    <td width="60%">
                        {{ object.addition_info }}
                    </td>
                </tr>
                {% endif %}

                <tr>
                    <th scope="row">Днів у виконанні</th>
                    <td>
                        {{ object.active_days_amount|add:object.time_after_update }}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Статус дослідження</th>
                    <td>
                        {% if object.executed %}<span class="text-primary">Закрите {{ object.date_executed }}</span> 
                        {% elif object.active %}<span class="text-success">Активне</span>
                        {% else %}<span class="text-secondary">Призупинене</span>{% endif %}
                    </td>
                </tr>
                <tr>
                    <th scope="row"></th>
                    <td>
                        <a type="button" class="btn btn-info modal-button"
                            href="{% url 'freports:edit_research' object.id %}?next=freports:research_detail">Редагувати основну інформацію</a>
                        <a type="button" class="btn btn-danger modal-button"
                            href="{% url 'freports:delete_research' object.id %}?next=freports:researches_list">Видалити дослідження</a>
                    </td>
                </tr> 
            </tbody>
        </table>
    </div>
</div>


{% endblock content %}

freports/templates/freports/research_form.html
{% extends "freports/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
<h2>{{ header }}</h2>
{% endblock title %}

{% block content %}

{% crispy form %}

{% endblock content %}