finance/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import permission_required

from . import views
from .views import (
    AccountList,
    AccountDetail,
    OrderDetail,
    IncomeList,
    IncomeCreate, 
    IncomeEdit, 
    IncomeDelete,
    ExecutionList,
    ExecutionCreate,
    ExecutionEdit,
    ExecutionDelete,
    )

urlpatterns = [
    # account URLs
    url(r'^accounts/$', 
        permission_required('admins')(AccountList.as_view()), 
        name='accounts_list'), 
    url(r'^account/(?P<pk>\d+)/detail/$', 
        permission_required('admins')(AccountDetail.as_view()),
        name='detail_account'),
    url(r'^accounts/add/$', views.add_account, 
        name='add_account'),
    url(r'^accounts/(?P<aid>\d+)/edit/$', views.edit_account,
        name='edit_account'),
    url(r'^accounts/(?P<aid>\d+)/delete/$', views.delete_account,
        name='delete_account'),

    # order URLs
    url(r'^orders/$', views.orders_list, 
        name='orders_list'),
    url(r'^orders/(?P<pk>\d+)/detail/$', 
        permission_required('admins')(OrderDetail.as_view()),
        name='detail_order'),   
    url(r'^orders/add/$', views.add_order,
        name='add_order'),
    url(r'^orders/(?P<oid>\d+)/edit/$', views.edit_order,
        name='edit_order'),
    url(r'^orders/(?P<oid>\d+)/delete/$', views.delete_order,
        name='delete_order'),

    # income URLs
    url(r'^incomes/$', 
        permission_required('admins')(IncomeList.as_view()), 
        name="incomes_list"),
    url(r'^incomes/add/$', 
        permission_required('admins')(IncomeCreate.as_view()),
        name="add_income"),
    url(r'^incomes/(?P<pk>\d+)/edit/$', 
        permission_required('admins')(IncomeEdit.as_view()),
        name="edit_income"),
    url(r'^incomes/(?P<pk>\d+)/delete/$', 
        permission_required('admins')(IncomeDelete.as_view()),
        name="delete_income"),

    # execution URLs
    url(r'^executions/$', 
        permission_required('admins')(ExecutionList.as_view()), 
        name='executions_list'),
    url(r'^executions/add/$', 
        permission_required('admins')(ExecutionCreate.as_view()),
        name="add_execution"),
    url(r'^executions/(?P<pk>\d+)/edit/$', 
        permission_required('admins')(ExecutionEdit.as_view()),
        name="edit_execution"),
    url(r'^executions/(?P<pk>\d+)/delete/$', 
        permission_required('admins')(ExecutionDelete.as_view()),
        name="delete_execution"),
]

app_name = 'finance'

freports/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views
from .views import (
    ResearchListView,
    ResearchDetailView, 
    ResearchCreate, 
    ResearchEdit,
    ResearchDelete
    )

urlpatterns = [
    # report urls
    url(r'^$', views.reports_list, 
        name='reports_list'),
    url(r'^add/new_report/$', views.add_new_report, 
        name='add_new_report'),
    url(r'^(?P<rid>\d+)/edit/$', views.report_edit, 
        name='report_edit'),
    url(r'^(?P<rid>\d+)/delete/$', views.delete_report, 
        name='delete_report'),
    url(r'^update_info/$', views.update_info, 
        name='reports_update'),

    # research urls
    url(r'^researches/$', ResearchListView.as_view(), 
        name='researches_list'),
    url(r'^researches/(?P<pk>\d+)/$', ResearchDetailView.as_view(), 
        name='research_detail'),
    url(r'^add/new_research/$', views.add_new_research, 
        name='add_new_research'),
    url(r'^researches/add/$', ResearchCreate.as_view(), 
        name="add_research"),
    url(r'^researches/(?P<pk>\d+)/edit/$', ResearchEdit.as_view(), 
        name='edit_research'),
    url(r'^researches/(?P<pk>\d+)/delete/$', ResearchDelete.as_view(), 
        name='delete_research'),

    # event urls
    url(r'^(?P<rid>\d+)/details/$', views.details_list, 
        name='report_detail'),
    url(r'^(?P<rid>\d+)/details/order/add/$', views.add_order, 
        name='add_order'),
    url(r'^(?P<rid>\d+)/details/add/(?P<kind>\w+)/$', 
        views.add_detail, name='add_detail'),
    url(r'^(?P<rid>\d+)/details/(?P<did>\d+)/edit/$', 
        views.edit_detail, name='edit_detail'),
    url(r'^(?P<rid>\d+)/details/(?P<did>\d+)/delete/$', 
        views.delete_detail, name='delete_detail'),
    url(r'^(?P<rid>\d+)/details/schedule/add/$',
        views.add_schedule, name='add_schedule'),
    url(r'^(?P<rid>\d+)/details/bill/add/$',
        views.add_bill, name='add_bill'),

    # participant urls
    url(r'^partisipants/$', views.participants_list, 
        name='participants_list'),
    url(r'^partisipants/(?P<rid>\d+)/detail/$', 
        views.participant_detail, name='participant_detail'),
    url(r'^(?P<rid>\d+)/partisipants/add/(?P<status>\w+)/$', 
        views.add_participant, name='add_participant'),
    url(r'^(?P<rid>\d+)/partisipants/(?P<did>\d+)/edit/$', 
        views.edit_participant, name='edit_participant'),
    url(r'^(?P<rid>\d+)/partisipants/(?P<did>\d+)/delete/$', 
        views.delete_participant, name='delete_participant'),

    # subject urls
    url(r'^subjects/$', views.subjects_list, 
        name='subjects_list'),
    url(r'^subjects/(?P<sid>\d+)/detail/$', views.subject_detail, 
        name='subject_detail'),
    url(r'^(?P<rid>\d+)/subjects/add/$', views.add_subject, 
        name='add_subject'),
    url(r'^(?P<rid>\d+)/subjects/(?P<sid>\d+)/edit/$', 
        views.edit_subject, name='edit_subject'),
    url(r'^(?P<rid>\d+)/subjects/(?P<sid>\d+)/delete/$', 
        views.delete_subject, name='delete_subject'),

    # contact urls
    url(r'^contacts/$', views.contacts_list, name='contacts_list'),
    url(r'^contacts/update/$', views.update_contacts_status, 
        name='contacts_update_status'),
    url(r'^contacts/(?P<cid>\d+)/detail/$', views.contact_detail, 
        name="contact_detail"),
    url(r'^contacts/add/$', views.add_contact, 
        name="add_contact"),
    url(r'^contacts/(?P<cid>\d+)/edit/$', views.edit_contact, 
        name="edit_contact"),
    url(r'^contacts/(?P<cid>\d+)/delete/$', views.delete_contact, 
        name="delete_contact"),

    # court urls
    url(r'^courts/$', views.courts_list, name='courts_list'),
    url(r'^courts/(?P<cid>\d+)/detail/$', views.court_detail, 
        name='court_detail'),
    url(r'^courts/add/$', views.add_court, 
        name='add_court'),
    url(r'^courts/(?P<cid>\d+)/edit/$', views.edit_court, 
        name='edit_court'),
    url(r'^courts/(?P<cid>\d+)/delete/$', views.delete_court, 
        name='delete_court'),

    # judge urls
    url(r'^judges/$', views.judges_list, name='judges_list'),
    url(r'^judges/(?P<jid>\d+)/detail/$', views.judge_detail, 
        name='judge_detail'),
    url(r'^judges/add/$', views.add_judge, 
        name='add_judge'),
    url(r'^judges/(?P<jid>\d+)/edit/$', views.edit_judge, 
        name='edit_judge'),
    url(r'^judges/(?P<jid>\d+)/delete/$', views.delete_judge, 
        name='delete_judge'),

    # task urls
    url(r'^tasks/$', views.tasks_list, name='tasks_list'),
    url(r'^tasks/change_status$', views.change_status_task, 
        name='change_status_task'),
    url(r'^tasks/today/$', views.tasks_today_list, 
        name='tasks_today_list'),
    url(r'^tasks/add/$', views.add_task, name='add_task'),
    url(r'^tasks/(?P<tid>\d+)/edit/$', views.edit_task, 
        name='edit_task'),
    url(r'^tasks/(?P<tid>\d+)/delete/$', views.delete_task, 
        name='delete_task'),
    url(r'^tasks/delete_old/$', views.delete_old_tasks, 
        name='delete_old_tasks'),
]

app_name = 'freports'

login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.login_auth, 
        name='form'),
    url(r'^logout/$', views.logout_auth, 
        name='out'),
    url(r'^attempts/$', views.login_attempts, 
        name='attempts'),
    url(r'^logs/$', views.login_logs, 
        name='logs'),
    url(r'^attempts/delete$', views.delete_old_attempts, 
        name='attempts_delete'),
]

app_name = 'login'

timeplanner/urls.py
from django.contrib import admin
from django.urls import path, include

# from freports.admin import admin_site
from business_card import views as business_card

urlpatterns = [
    path('', business_card.first_page, name='first_page'),
    path('freports/', include('freports.urls', namespace='freports')),
    path('login/', include('login.urls', namespace='login')),
    path('finance/', include('finance.urls', namespace='finance')),
    path('admin/', admin.site.urls),

]

finance/models/account.py
from __future__ import unicode_literals

from django.db import models

from .income import Income
from .execution import Execution


class Account(models.Model):
    STATUS_VARIANT = (
        ('self', u'Особистий'),
        ('work', u'Робочий'),
    )

    class Meta(object):
        verbose_name=u"Рахунок"
        verbose_name_plural=u"Рахунки"

    title = models.CharField(
        verbose_name=u"Назва рахунку",
        max_length=256,
        blank=False,
        null=False)

    cash = models.BooleanField(
        verbose_name=u"Готівка",
        blank=False,
        null=False)

    status = models.CharField(
        verbose_name = u"Статус рахунку",
        max_length=256,
        choices = (("self", u"Особистий"), ("work", u"Робочий")),
        blank=False,
        null=False)

    credit_cash = models.IntegerField(
        verbose_name=u"Кошти в кредитах",
        blank=True,
        null=True)

    def __str__(self):
        return u"Рахунок {} ({})".format(
            self.title, dict(self.STATUS_VARIANT)[self.status])

    def remainder(self):
        account = self
        incomes = Income.objects.filter(account=account)
        executions = Execution.objects.filter(account=account)
        total_sum = 0
        for income in incomes:
            total_sum += income.amount
        for execution in executions:
            total_sum -= execution.amount
        return total_sum

finance/models/execution.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone

class Execution(models.Model):
    class Meta(object):
        verbose_name=u"Виконання"
        verbose_name_plural=u"Виконання"

    order = models.ForeignKey(
        "Order",
        verbose_name=u"Замовлення",
        blank=False,
        null=False,
        on_delete=models.PROTECT)

    date = models.DateField(
        verbose_name=u"Дата виконання",
        blank=False,
        null=False,
        default=timezone.now)

    account = models.ForeignKey(
        "Account",
        verbose_name=u"Цільовий рахунок",
        blank=False,
        null=False,
        on_delete=models.PROTECT)

    amount = models.IntegerField(
        verbose_name=u"Сума закриття",
        blank=False,
        null=False,
        validators=[MinValueValidator(100),])

    closed_tasks = models.CharField(
        max_length=256,
        blank=True,
        null=True,
        verbose_name=u"Закриті таски")

    def __str__(self):
        return u"Виконання по замовленню {}".format(
            self.order.name)

    def model_name(self):
        return 'Виконання'

finance/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.db import models

from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Button

from .models import Income, Order, Account, Execution

class IncomeForm(forms.ModelForm):

    date = forms.DateField(
        label=u"Дата отримання",
        widget=forms.DateInput(
            format=('%Y-%m-%d'),
            attrs={
                'id': 'inputDate3',
                'data-toggle': 'datetimepicker',
                'data-target': "#inputDate3"}
            )
        )

    def __init__(self, *args, **kwargs):
        super(IncomeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)

        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.label_class = 'col-sm-4'
        self.helper.field_class = 'col-sm-6'

        self.helper.layout.append(Layout(
            FormActions(
                Submit('submit', u'Зберегти'),
                Button('submit', u'Скасувати', 
                    css_class='btn-link'),
            )
        ))

    class Meta:
        model = Income
        fields = ['order', 'date', 'account', 'amount', 'payer']

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        order = self.cleaned_data['order']
        remainder = order.total_sum - order.paid_sum + self.initial.get('amount', 0)
        if amount > remainder:
            raise forms.ValidationError(
                u"Сума усіх надходжень не може бути більша кошторисної вартості замовлення!")
        return amount


class ExecutionForm(forms.ModelForm):
    date = forms.DateField(
        label=u"Дата виконання",
        widget=forms.DateInput(
            format=('%Y-%m-%d'),
            attrs={
                'id': 'inputDate3',
                'data-toggle': 'datetimepicker',
                'data-target': "#inputDate3"}
            )
        )

    def __init__(self, *args, **kwargs):
        super(ExecutionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)

        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.label_class = 'col-sm-4'
        self.helper.field_class = 'col-sm-6'

        self.helper.layout.append(Layout(
            FormActions(
                Submit('submit', u'Зберегти'),
                Button('submit', u'Скасувати', 
                    css_class='btn-link'),
            )
        ))

    class Meta:
        model = Execution
        fields = ['order', 'date', 'account', 'amount', 'closed_tasks']

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        order = self.cleaned_data['order']
        remaider = order.total_sum - order.done_sum + self.initial.get('amount', 0)
        if amount > remaider:
            raise forms.ValidationError(
                u"Сума усіх виконань не може бути більша кошторисної вартості замовлення!")
        return amount

    def clean_date(self):
        date = self.cleaned_data['date']
        order_id = self.data['order']
        incomes = Income.objects.filter(order=order_id)
        if incomes:
            first_income = incomes.order_by('date').first()
            if date < first_income.date:
                raise forms.ValidationError(
                    u"Виконання не може бути раніше дня першого надходження по замовленню")
        return date

        

finance/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Account, Order

@login_required(login_url='/login/')
def accounts_list(request):
    accounts = Account.objects.all().order_by('title')
    orders = Order.objects.all()
    content = {}
    content['total_sum'] = 0
    content['paid_sum'] = 0
    content['done_sum'] = 0
    for order in orders:
        content['total_sum'] += order.total_sum
        content['paid_sum'] += order.paid_sum
        content['done_sum'] += order.done_sum
    header = u'Список рахунків'
    return render(request, 'finance/accounts_list.html', 
        {'accounts': accounts, 'header': header, 'orders': orders,
         'content': content})

@login_required(login_url='/login/')
def add_account(request):
    header = u'Додавання рахунку'
    if request.method == 'POST':
        if request.POST.get('save_button'):
            info = valid_data(request.POST)
            checked_data = info['new_account']
            errors = info['errors']
            if errors:
                messages.error(request, u"Виправте наступні помилки")
                return render(request, 'finance/account_form.html', 
                    {'header': header, 'errors': errors, 'content': checked_data})
            else:
                new_account = Account(**checked_data)
                new_account.save()
                messages.success(request, u"Рахунок {} успішно доданий".format(new_account.title))
        else:
            messages.warning(request, u"Додавання рахунку скасовано")
        return HttpResponseRedirect(reverse('finance:accounts_list'))
    else:
        return render(request, 'finance/account_form.html', 
        {'header': header})

def valid_data(form_data):
    new_account, errors = {}, {}
    title = form_data.get('title')
    if title:
        new_account['title'] = title
    else:
        errors['title'] = u"Назва рахунку є обов'язковою"

    total_sum = form_data.get('total_sum')
    if total_sum:
        new_account['total_sum'] = total_sum
    else:
        errors['total_sum'] = u"Сума на рахунку є обов'язковою"

    credit_cash = form_data.get('credit_cash')
    if credit_cash:
        try:
            new_account['credit_cash'] = int(credit_cash)
        except ValueError:
            new_account['credit_cash'] = credit_cash
            errors['credit_cash'] = u"Будь-ласка введіть ціле число"

    cash = form_data.get('cash')
    if cash:
        new_account['cash'] = True
    else:
        new_account['cash'] = False

    status = form_data.get('status')
    new_account['status'] = status

    return {'new_account': new_account, 'errors': errors}

finance/templates/finance/accounts_list.html
{% extends "freports/base.html" %}

{% block sidebar %}
{% include 'finance/sidebar.html' %}
{% endblock sidebar %}

{% block title %}
<div class="col">
    <span class="h1">Список рахунків</span> <span class="badge badge-danger">Beta</span>
    <a class="btn btn-outline-info modal-button"
        id="add-report" href="{% url 'finance:add_account' %}">Додати рахунок</a>
</div>
{% endblock title %}

{% block extra_messages %}
{% endblock extra_messages %}

{% block content %}

{% if accounts %}
{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
<table class="table table-hover table-responsive-lg">
    <thead class="thead-light">
        <tr>
            <th scope="col">Назва рахунку</th>
            <th scope="col">Вид рахунку</th>
            <th scope="col">Вид зберезення</th>
            <th scope="col">Невиконаний залишок</th>
            <th scope="col">Надано в кредит</th>
            <th scope="col" class="group-buttons"></th>
<!--             <th scope="col">Дії</th> -->
        </tr>
    </thead>
{% endwith %}

    <tbody>

        {% for account in accounts %}
        <tr>

            <th scope="row"><a href="{% url 'finance:detail_account' account.id %}">{{ account.title }}</a></th>
            <td>{{ account.get_status_display }}</td>
            <td>{% if account.cash %}Готівка{% else %}Безнал{% endif %}</td>
            <td>{{ account.remainder }}</td>
            <td>{% if account.credit_cash %}{{ account.credit_cash }}{% endif %}</td>
            <td class="group-buttons">
                <a class="modal-button" href="{% url 'finance:delete_account' account.id %}"><i class="fa fa-trash-o"></i></a>
                <a class="modal-button" href="{% url 'finance:edit_account' account.id %}"><i class="fa fa-pencil"></i></a>
            </td>       
        </tr>
        {% endfor %}



    </tbody>
</table>

{% else %}
<p>Ще немає даних</p>
{% endif %}

{% endblock content %}

finance/templates/finance/form.html
{% extends "freports/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
<div class="col">
    <h2>{{ header }}</h2>
</div>
{% endblock title %}

{% block content %}

{% crispy form %}

{% endblock content %}

finance/templates/finance/order_detail.html
{% extends "freports/base.html" %}

{% block title %}

<div class="col-3">
    <a type="button" class="btn btn-outline-dark mb-3"
    href="{% url 'finance:orders_list' %}">Повернутись до списку замовлень</a>
</div>
<div class="col-9">
    <span class="h2">Список транзакцій по замовленню {{ object.name }}</span> <span class="badge badge-danger">Beta</span>
</div>

{% endblock title %}

{% block extra_messages %}
{% endblock extra_messages %}

{% block content %}

<div class="row">
    <div class="col">
<!--     <h3>Статус замовлення</h3>  -->
    {% if object.report %}
    
    {% endif %}
    </div>

</div>

<div class="row">
    <div class="col">
        <table class="table table-hover table-responsive-lg">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Дата</th>
                    <th scope="col">Тип транзакції</th>
                    <th scope="col">Рахунок</th>
                    <th scope="col">Додаткова інформація</th>
                    <th scope="col">Сума</th>
                    <th scope="col" class="group-buttons"></th>
                </tr>
            </thead>
            <tbody>
                {% if object_list %}
                {% for transaction in object_list %}
                <tr class="{% if transaction.model_name == 'Виконання' %}text-danger{% else %}text-success{% endif %}">
                    <th scope="row">{{ transaction.date }}</th>
                    <td>{{ transaction.model_name }}</td>
                    <td>{{ transaction.account.title }}</td>
                    <td>
                        {% if transaction.model_name == "Виконання" %}
                        {% firstof transaction.closed_tasks '-' %}
                        {% else %}
                        {% firstof transaction.payer '-' %}
                        {% endif %}
                    </td>
                    <td>{{ transaction.amount }}</td>
                    <td class="group-buttons">
                        {% if transaction.model_name == "Виконання" %}
                            <a href="{% url 'finance:delete_execution' transaction.id %}?next_url=detail_order" class="modal-button"><i class="fa fa-trash-o"></i></a>
                            <a href="{% url 'finance:edit_execution' transaction.id %}?next_url=detail_order" class="modal-button"><i class="fa fa-pencil"></i></a>
                        {% else %}
                            <a href="{% url 'finance:delete_income' transaction.id %}?next_url=detail_order" class="modal-button"><i class="fa fa-trash-o"></i></a>
                            <a href="{% url 'finance:edit_income' transaction.id %}?next_url=detail_order" class="modal-button"><i class="fa fa-pencil"></i></a>
                        {% endif %}
                    </td> 
                </tr>
                {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="5" class="text-center">
                            <h4>Ще немає даних</h4>
                        </td>
                    </tr>
                {% endif %}
                {% if object.remainder %}
                <tr>
                    <td colspan="3"></td>
                    <th scope="row" class="text-center table-info h5">Невиконаний залишок</th>
                    <td class="{% if object.remainder >= 0 %}text-success{% else %}text-danger {% endif %} table-info h5">{{ object.remainder }}</td>
                </tr>
                {% endif %}
                <tr>
                    <td colspan="3">
                        {% if object.paid_sum < object.total_sum %}
                        <a class="btn btn-outline-success mr-3 modal-button" 
                            href="{% url 'finance:add_income' %}?order={{ object.id }}">Додати надходження</a>
                        {% endif %}

                        {% if object.done_sum < object.total_sum and object.paid_sum > object.done_sum %}
                        <a class="btn btn-outline-danger modal-button" 
                            href="{% url 'finance:add_execution' %}?order={{ object.id }}">Додати виконання</a>
                        {% endif %}
                    </td>
                    <th scope="row" class="text-center h5">Загальна сума</th>
                    <td class="h5">{{ object.total_sum }}</td>
                    <td class="group-buttons">
                        <a href="{% url 'finance:edit_order' object.id %}?next_url=detail_order" class="modal-button"><i class="fa fa-pencil mr-3"></i></a>
                    </td>
                </tr>
            </tbody>
        </table>

        {% if object.report %}
        <a class="btn btn-outline-info btn-sm" href="{% url 'freports:report_detail' object.report.id %}">&#x25c1 Інформація про провадженню №{{ object.report.full_number }}</a>
        {% endif %}
    </div>
</div>



{% endblock content %}

finance/templates/finance/orders_list.html
{% extends "freports/base.html" %}

{% block sidebar %}
{% include 'finance/sidebar.html' %}
{% endblock sidebar %}

{% block title %}
<div class="col">
    <span class="h1">Список замовлень</span> <span class="badge badge-danger">Beta</span>
    <a class="btn btn-outline-info modal-button" id="add-report"
        href="{% url 'finance:add_order' %}">Додати замовлення</a>
</div>
{% endblock title %}

{% block extra_messages %}
{% endblock extra_messages %}

{% block content %}

<nav class="nav nav-pills nav-justified" id="navbar-list">
    <a class="nav-item nav-link {% if request.GET.status == 'all' %}active{% endif %}" href="{% url 'finance:orders_list' %}?status=all">Усі <span class="badge badge-info">{{ content.all_orders }}</span></a>
    <a class=" nav-item nav-link {% if not request.GET.status %}active{% endif %}" href="{% url 'finance:orders_list' %}">Активні <span class="badge badge-success">{{ content.active_orders }}</span></a>
    <a class="nav-link nav-item {% if request.GET.status == 'inactive' %}active{% endif %}" href="{% url 'finance:orders_list' %}?status=inactive">Призупинені <span class="badge badge-secondary">{{ content.inactive_orders }}</span></a>
    <a class="nav-link nav-item {% if request.GET.status == 'done' %}active{% endif %}" href="{% url 'finance:orders_list' %}?status=done">Виконані <span class="badge badge-light">{{ content.done_orders }}</span></a>
</nav>

{% if orders %}
<table class="table table-hover table-responsive-lg">
    <thead class="thead-light">
        <tr>
            <th scope="col">Назва замовлення</th>
            <th scope="col">Провадження</th>
            <th scope="col">Деталі</th>
            <th scope="col">Кошторисна вартість</th>
            <th scope="col">Оплачено</th>
            <th scope="col">Виконано</th>
            {% if not request.GET.status or request.GET.status == 'all' %}
            <th scope="col">Невиконаний залишок</th>
            {% endif %}
            <th scope="col">Кількість тасків</th>
            <th scope="col" class="group-buttons"></th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
        <tr>
            <th scope="row" width='15%'>
                <a class="{% if order.paid_sum > order.done_sum %}text-success{% elif order.paid_sum < order.total_sum %}text-secondary{% else %}text-info{% endif %}" href="{% url 'finance:detail_order' order.id %}">
                    {{ order.name }}
                </a>
            </th>
            <td>
                {% if order.report %}
                <a href="{% url 'freports:report_detail' order.report.id %}">
                    {{ order.report.full_number }}
                </a>
                {% endif %}
            </td>
            <td width='20%'>
                {% if order.report %}
                {{ order.report.short_info|truncatechars:30 }}
                {% endif %}
            </td>
            <td>{{ order.total_sum }}</td>
            <td>{{ order.paid_sum }}</td>
            <td>{{ order.done_sum }}</td>
            {% if not request.GET.status or request.GET.status == 'all' %}
            <td>{{ order.remainder }}</td>
            {% endif %}
            <td width='5%'>
            {% if order.tasks_number %}
            {{ order.tasks_number }}
            {% else %}
            -
            {% endif %}
            </td>
            <td class="group-buttons">
                <a href="{% url 'finance:delete_order' order.id %}" class="modal-button"><i class="fa fa-trash-o"></i></a>
                <a href="{% url 'finance:edit_order' order.id %}" class="modal-button"><i class="fa fa-pencil"></i></a>
            </td>       
        </tr>
        {% endfor %}
        <tr class="table-secondary">
            <th colspan="3" class="text-center">
                Всього
                {% if request.GET.status == 'inactive' %}
                    по призупинених замовленнях
                {% elif request.GET.status == 'done' %}
                    по виконаних замовленнях
                {% elif not request.GET.status %}
                    по активних замовленнях
                {% endif %}

            </th>
            <td><strong>{{ content.total_sum }}</strong></td>
            <td><strong>{{ content.paid_sum }}</strong></td>
            <td><strong>{{ content.done_sum }}</strong></td>
            {% if not request.GET.status or request.GET.status == 'all' %}
            <td colspan="2"><strong>{{ content.remainder_sum }}</strong></td>
            {% endif %}
        </tr>

    </tbody>
</table>

{% else %}
<p>Ще немає даних</p>
{% endif %}

{% endblock content %}