freports/api/urls.py
from django.conf.urls import url

from .views import (
    ReportListApiView, 
    ReportDetailApiView,
    ReportCreateAwardApiView
    )

urlpatterns = [
    # report urls
    url(r'^$', ReportListApiView.as_view(), 
        name='reports_list'),
    url(r'^(?P<pk>\d+)/$', ReportDetailApiView.as_view(),
        name='report_detail'),
    url(r'^create/$', ReportCreateAwardApiView.as_view(), 
        name='report_create')
]

freports/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views
from .views import (
    ResearchListView,
    ResearchDetailView, 
    ResearchCreate, 
    ResearchEdit,
    ResearchDelete
    )

urlpatterns = [
    # report urls
    url(r'^$', views.reports_list, 
        name='reports_list'),
    url(r'^add/new_report/$', views.add_new_report, 
        name='add_new_report'),
    url(r'^(?P<rid>\d+)/edit/$', views.report_edit, 
        name='report_edit'),
    url(r'^(?P<rid>\d+)/delete/$', views.delete_report, 
        name='delete_report'),
    url(r'^update_info/$', views.update_info, 
        name='reports_update'),

    # research urls
    url(r'^researches/$', ResearchListView.as_view(), 
        name='researches_list'),
    url(r'^researches/(?P<pk>\d+)/$', ResearchDetailView.as_view(), 
        name='research_detail'),
    url(r'^add/new_research/$', views.add_new_research, 
        name='add_new_research'),
    url(r'^researches/add/$', ResearchCreate.as_view(), 
        name="add_research"),
    url(r'^researches/(?P<pk>\d+)/edit/$', ResearchEdit.as_view(), 
        name='edit_research'),
    url(r'^researches/(?P<pk>\d+)/delete/$', ResearchDelete.as_view(), 
        name='delete_research'),

    # event urls
    url(r'^(?P<rid>\d+)/details/$', views.details_list, 
        name='report_detail'),
    url(r'^(?P<rid>\d+)/details/order/add/$', views.add_order, 
        name='add_order'),
    url(r'^(?P<rid>\d+)/details/add/(?P<kind>\w+)/$', 
        views.add_detail, name='add_detail'),
    url(r'^(?P<rid>\d+)/details/(?P<did>\d+)/edit/$', 
        views.edit_detail, name='edit_detail'),
    url(r'^(?P<rid>\d+)/details/(?P<did>\d+)/delete/$', 
        views.delete_detail, name='delete_detail'),
    url(r'^(?P<rid>\d+)/details/schedule/add/$',
        views.add_schedule, name='add_schedule'),
    url(r'^(?P<rid>\d+)/details/bill/add/$',
        views.add_bill, name='add_bill'),

    # participant urls
    url(r'^partisipants/$', views.participants_list, 
        name='participants_list'),
    url(r'^partisipants/(?P<rid>\d+)/detail/$', 
        views.participant_detail, name='participant_detail'),
    url(r'^(?P<rid>\d+)/partisipants/add/(?P<status>\w+)/$', 
        views.add_participant, name='add_participant'),
    url(r'^(?P<rid>\d+)/partisipants/(?P<did>\d+)/edit/$', 
        views.edit_participant, name='edit_participant'),
    url(r'^(?P<rid>\d+)/partisipants/(?P<did>\d+)/delete/$', 
        views.delete_participant, name='delete_participant'),

    # subject urls
    url(r'^subjects/$', views.subjects_list, 
        name='subjects_list'),
    url(r'^subjects/(?P<sid>\d+)/detail/$', views.subject_detail, 
        name='subject_detail'),
    url(r'^(?P<rid>\d+)/subjects/add/$', views.add_subject, 
        name='add_subject'),
    url(r'^(?P<rid>\d+)/subjects/(?P<sid>\d+)/edit/$', 
        views.edit_subject, name='edit_subject'),
    url(r'^(?P<rid>\d+)/subjects/(?P<sid>\d+)/delete/$', 
        views.delete_subject, name='delete_subject'),

    # contact urls
    url(r'^contacts/$', views.contacts_list, name='contacts_list'),
    url(r'^contacts/update/$', views.update_contacts_status, 
        name='contacts_update_status'),
    url(r'^contacts/(?P<cid>\d+)/detail/$', views.contact_detail, 
        name="contact_detail"),
    url(r'^contacts/add/$', views.add_contact, 
        name="add_contact"),
    url(r'^contacts/(?P<cid>\d+)/edit/$', views.edit_contact, 
        name="edit_contact"),
    url(r'^contacts/(?P<cid>\d+)/delete/$', views.delete_contact, 
        name="delete_contact"),

    # court urls
    url(r'^courts/$', views.courts_list, name='courts_list'),
    url(r'^courts/(?P<cid>\d+)/detail/$', views.court_detail, 
        name='court_detail'),
    url(r'^courts/add/$', views.add_court, 
        name='add_court'),
    url(r'^courts/(?P<cid>\d+)/edit/$', views.edit_court, 
        name='edit_court'),
    url(r'^courts/(?P<cid>\d+)/delete/$', views.delete_court, 
        name='delete_court'),

    # judge urls
    url(r'^judges/$', views.judges_list, name='judges_list'),
    url(r'^judges/(?P<jid>\d+)/detail/$', views.judge_detail, 
        name='judge_detail'),
    url(r'^judges/add/$', views.add_judge, 
        name='add_judge'),
    url(r'^judges/(?P<jid>\d+)/edit/$', views.edit_judge, 
        name='edit_judge'),
    url(r'^judges/(?P<jid>\d+)/delete/$', views.delete_judge, 
        name='delete_judge'),

    # task urls
    url(r'^tasks/$', views.tasks_list, name='tasks_list'),
    url(r'^tasks/change_status$', views.change_status_task, 
        name='change_status_task'),
    url(r'^tasks/today/$', views.tasks_today_list, 
        name='tasks_today_list'),
    url(r'^tasks/add/$', views.add_task, name='add_task'),
    url(r'^tasks/(?P<tid>\d+)/edit/$', views.edit_task, 
        name='edit_task'),
    url(r'^tasks/(?P<tid>\d+)/delete/$', views.delete_task, 
        name='delete_task'),
    url(r'^tasks/delete_old/$', views.delete_old_tasks, 
        name='delete_old_tasks'),
]

app_name = 'freports'

login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.login_auth, 
        name='form'),
    url(r'^logout/$', views.logout_auth, 
        name='out'),
    url(r'^attempts/$', views.login_attempts, 
        name='attempts'),
    url(r'^logs/$', views.login_logs, 
        name='logs'),
    url(r'^attempts/delete$', views.delete_old_attempts, 
        name='attempts_delete'),
]

app_name = 'login'

timeplanner/urls.py
from django.contrib import admin
from django.urls import path, include

# from freports.admin import admin_site
from business_card import views as business_card

urlpatterns = [
    path('', business_card.first_page, name='first_page'),
    path('freports/', include('freports.urls', namespace='freports')),
    path('login/', include('login.urls', namespace='login')),
    path('finance/', include('finance.urls', namespace='finance')),
    path('admin/', admin.site.urls),

]

ang/views.py
import os

from django.conf import settings
from django.http import HttpResponse, Http404
from django.views import View

class AngularTemplateView(View):
    def get(self, request, item='report-list', *args, **kwargs):
        template_dir_path = settings.TEMPLATES[0]["DIRS"][0]
        final_path = os.path.join(template_dir_path, "ang",
            item + '.html')
        try:
            html = open(final_path)
            return HttpResponse(html)
        except:
            raise Http404

freports/api/views.py
from rest_framework.filters import OrderingFilter
from rest_framework.generics import (
    ListAPIView, 
    RetrieveAPIView,
    CreateAPIView,
    )
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView

from .serializers import (
    ReportListSerializer, 
    ReportDetailSerializer,
    ReportCreateAwardSerializer
    )
from ..models import Report

class ReportListApiView(ListAPIView):
    serializer_class = ReportListSerializer
    permission_classes = (IsAuthenticated,)
    queryset = Report.objects.all()
    filter_backends = (OrderingFilter,)
    ordering_fields = ('number', 'address')
    ordering = ('number',)

class ReportDetailApiView(RetrieveAPIView):
    serializer_class = ReportDetailSerializer
    permission_classes = (IsAuthenticated,)
    queryset = Report.objects.all()

class ReportCreateAwardApiView(CreateAPIView):
    queryset = Report.objects.all()
    serializer_class = ReportCreateAwardSerializer
    permission_classes = (IsAuthenticated,)

    def perform_create(self, serializer):
        serializer.save(
            plaintiff='-',
            defendant='-',
            address='-',
            object_name='-',
            research_kind='-',
            active=None
        )

freports/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from itertools import chain
from datetime import date

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

from .models import ForensicReport

def reports_list(request):
    if request.GET.get('executed'):
        reports = ForensicReport.objects.all().order_by('number').filter(executed=True)
    else:
        reports = ForensicReport.objects.all().order_by('number').filter(executed=False)
    order_by = request.GET.get('order_by')
    reverse = request.GET.get('reverse')
    if order_by:
        reports = reports.order_by(order_by)
        if reverse:
            reports = reports.reverse()
    else:
        reports_top = reports.filter(active=True)
        reports_low = reports.filter(active=False)
        reports = list(chain(reports_top, reports_low))
    for report in reports:
        if request.GET.get('executed'):
            days_amount = report.date_executed - report.date_arrived
            report.days_amount = days_amount.days
        else:
            days_amount = date.today() - report.date_arrived
            report.days_amount = days_amount.days
    return render(request, 'freports/reports_list.html', {'reports': reports})

def add_report(request):
    header = u'Додавання провадження'

    if request.method == 'POST':
        if request.POST.get('save_button'):
            validate_data = valid_report(request.POST)
            errors = validate_data['errors']
            new_report = validate_data['data_report']

            if errors:
                messages.error(request, "Виправте наступні недоліки")
                return render(request, 'freports/add_report.html', {'header': header, 'errors': errors,
                    'content': new_report})

            else:
                new_report = ForensicReport(**new_report)
                new_report.save()
                messages.success(request, "Провадження №%s/017 успішно додане" % new_report.number)

        elif request.POST.get('cancel_button'):
            messages.warning(request, "Додавання провадження скасовано")

        return HttpResponseRedirect(reverse('forensic_reports_list'))

    else:
        return render(request, 'freports/add_report.html', {'header': header})


def edit_report(request, rid):
    header = 'Редагування провадження'
    content = ForensicReport.objects.get(pk=rid)

    if request.method == 'POST':
        if request.POST.get('save_button'):
            current_report = content

            validate_data = valid_report(request.POST)
            errors = validate_data['errors']
            new_report = validate_data['data_report']

            if errors:
                messages.error(request, "Виправте наступні недоліки")
                return render(request, 'freports/add_report.html', {'header': header, 'content': new_report,
                    'errors': errors})

            else:
                current_report.number = new_report['number']
                current_report.address = new_report['address']
                current_report.plaintiff = new_report['plaintiff']
                current_report.defendant = new_report['defendant']
                current_report.object_name = new_report['object_name']
                current_report.research_kind = new_report['research_kind']
                current_report.active = new_report['active']
                current_report.date_arrived = new_report['date_arrived']
                current_report.executed = new_report['executed']
                try:
                    current_report.date_executed = new_report['date_executed']
                except KeyError:
                    pass
                current_report.save()
                messages.success(request, "Провадження №%s/017 успішно відкориговане" % current_report.number)

        elif request.POST.get('cancel_button'):
            messages.warning(request, "Редагування провадження скасовано")

        return HttpResponseRedirect(reverse('forensic_reports_list'))

    else:
        content.date_arrived = content.date_arrived.isoformat()
        if content.executed:
            content.date_executed = content.date_executed.isoformat()
        return render(request, 'freports/add_report.html', {'header': header, 'content': content})


def delete_report(request, rid):
    if request.method == 'GET':
        report = ForensicReport.objects.get(pk=rid)
        return render(request, 'freports/delete_report.html', {'report': report})
    elif request.method == 'POST':
        if request.POST.get('delete_button'):
            current_report = ForensicReport.objects.get(pk=rid)
            current_report.delete()
            messages.success(request, "Провадження №%s/017 успішно видалено" % current_report.number)
        elif request.POST.get('cancel_button'):
            messages.warning(request, "Видалення провадження скасовано")

        return HttpResponseRedirect(reverse('forensic_reports_list'))

def valid_report(data_post):
    errors = {}
    new_report = {}

    date_arrived = data_post.get('date_arrived')
    if not date_arrived:
        errors['date_arrived'] = u"Дата надходження є обов'язковою"
    else:
        try:
            new_report['date_arrived'] = date_arrived
        except ValueError:
            errors['date_arrived'] = u"Введіть коректний формат дати"

    report_number = data_post.get('number')
    if not report_number:
        errors['number'] = u"Номер висновку є обов'язковим"
    else:
        try:
            new_report['number'] = int(report_number)
        except ValueError:
            new_report['number'] = report_number
            errors['number'] = u"Будь-ласка введіть число"

    address = data_post.get('address')
    if not address:
        errors['address'] = u"Адреса об'єкту є обов'язковою"
    else:
        new_report['address'] = address

    plaintiff = data_post.get('plaintiff')
    if not plaintiff:
        errors['plaintiff'] = u"Прізвище позивача є обов'язковим"
    else:
        new_report['plaintiff'] = plaintiff

    defendant = data_post.get('defendant')
    if not defendant:
        errors['defendant'] = u"Прізвище відповідача є обов'язковим"
    else:
        new_report['defendant'] = defendant

    object_name = data_post.get('object_name')
    if not object_name:
        errors['object_name'] = u"Тип об'єкту є обов'язковим"
    else:
        new_report['object_name'] = object_name

    research_kind = data_post.get('research_kind')
    if not research_kind:
        errors['research_kind'] = u"Вид дослідження є обов'язковим"
    else:
        new_report['research_kind'] = research_kind

    active = data_post.get('active')
    if active:
        if active == 'executed':
            new_report['active'] = False
            new_report['executed'] = True
        else:
            new_report['active'] = active
            new_report['executed'] = False

    date_executed = data_post.get('date_executed')
    if date_executed:
        new_report['date_executed'] = data_post.get('date_executed')

    return {'errors': errors, 'data_report': new_report}

freports/views/days_counter.py
# days count
from datetime import date, datetime

from ..models import ReportEvents

def check_active(report):
    details = ReportEvents.objects.filter(report=report).order_by(
        'date', 'id')
    last_detail = details[details.count() - 1]
    if last_detail.name == 'done':
        report.active = False
        report.executed = True
        report.date_executed = last_detail.date
    elif last_detail.activate:
        report.active = True
        report.executed = False
    else:
        report.active = False
        report.executed = False

    return report

def days_count(report, status):
    events = ReportEvents.objects.filter(report=report).order_by(
        'date', 'id')
    days_amount = 0
    if events.count() > 0:
        event_activate = False
        last_event = events.reverse()[0]
        if status == 'active':
            event_activate = True
            before_event = events[0]
            if events.count() > 1:
                for event in events:
                    if event.activate != True and before_event.activate == True:
                        time = event.date - before_event.date
                        days_amount += time.days
                    before_event = event
            if before_event.activate:
                time = date.today() - before_event.date
                days_amount += time.days

        if status != 'active' and last_event.activate == False:
            time = date.today() - last_event.date
            days_amount += time.days

    return days_amount

def update_dates_info(reports):
    reports = reports.filter(executed=False)
    last_update = reports[0].change_date
    time_amount = date.today() - last_update
    if time_amount == 0:
        return True
    for report in reports:
        report.change_date = date.today()
        if report.active:
            report.active_days_amount = days_count(report, 'active')
        else:
            report.waiting_days_amount = days_count(report, 'waiting')
        report.save()

templates/ang/base.html
{% load static %}
<!DOCTYPE html>
<html lang="uk" ng-app="reports">
<head>
    <base href="/angular/">
    <meta charset="UTF-8" />
    <title>ForensicManager</title>
    <link rel="shortcut icon" href="{{ PORTAL_URL }}{% static 'apple-icon-60x60.png' %}">

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700|Nunito:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" 
        href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0/css/tempusdominus-bootstrap-4.min.css" />
    <link rel="stylesheet" href="{{ PORTAL_URL }}{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="{{ PORTAL_URL }}{% static 'css/sidebar.css' %}" type="text/css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.7.5/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular-cookies.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.7.5/angular-resource.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.7.5/angular-route.js"></script>

    <script src="{{ PORTAL_URL }}{% static 'js/external/dirPagination.js' %}"></script>

    <script src="{{ PORTAL_URL }}{% static 'js/app/app.module.js' %}"></script>
    <script src="{{ PORTAL_URL }}{% static 'js/app/app.config.js' %}"></script>

    <script src="{{ PORTAL_URL }}{% static 'js/app/core/report/report.module.js' %}"></script>
    <script src="{{ PORTAL_URL }}{% static 'js/app/core/report/report.service.js' %}"></script>

    <script src="{{ PORTAL_URL }}{% static 'js/app/core/interceptors/interceptors.module.js' %}"></script>
    <script src="{{ PORTAL_URL }}{% static 'js/app/core/interceptors/login-required.service.js' %}"></script>

    <script src="{{ PORTAL_URL }}{% static 'js/app/report-list/report-list.module.js' %}"></script>
    <script src="{{ PORTAL_URL }}{% static 'js/app/report-list/report-list.component.js' %}"></script>

    <script src="{{ PORTAL_URL }}{% static 'js/app/report-detail/report-detail.module.js' %}"></script>
    <script src="{{ PORTAL_URL }}{% static 'js/app/report-detail/report-detail.component.js' %}"></script>

    <script src="{{ PORTAL_URL }}{% static 'js/app/utils/nav-bar/nav-bar.module.js' %}"></script>
    <script src="{{ PORTAL_URL }}{% static 'js/app/utils/nav-bar/nav-bar.directive.js' %}"></script>

    <script src="{{ PORTAL_URL }}{% static 'js/app/utils/side-bar/side-bar.module.js' %}"></script>
    <script src="{{ PORTAL_URL }}{% static 'js/app/utils/side-bar/side-bar.directive.js' %}"></script>

    <script src="{{ PORTAL_URL }}{% static 'js/app/login-detail/login-detail.module.js' %}"></script>
    <script src="{{ PORTAL_URL }}{% static 'js/app/login-detail/login-detail.component.js' %}"></script>

</head>


<body>

    <nav-bar ng-hide="hideNavBars"></nav-bar>

    <div class="wrapper">
        <side-bar ng-class="{ 'active': ! showSidebar }"></side-bar>

        <div id="content" class="container">
            <div class="row">
                <div class="col">
                    <button type="button" id="sidebarCollapse" class="navbar-btn" show-sidebar ng-click="showSidebar = ! showSidebar" ng-class="{ 'active': ! showSidebar }" ng-hide="hideNavBars">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div ng-view></div>
                </div>
            </div>

            <div class="row" id="footer" ng-hide="hideNavBars">
                <div class="col-12">
                    <hr />
                    <p>Time Planner, 2017-2019 &copy; <a href="#">Адмінка</a></p>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
    <script type="text/javascript" 
        src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0/js/tempusdominus-bootstrap-4.min.js">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/uk.js"></script>
</body>

templates/ang/freports.html
{% extends "freports/base.html" %}

{% block sidebar %}
<!-- Sidebar -->
<nav id="sidebar" {% if request.COOKIES.sidebar == 'active' %}class="active"{% endif %}>
    <div>
        <div class="sidebar-header">
            <h2 class="text-center">Провадження</h2>
        </div>

        <ul class="list-unstyled components">
            <li class="active">
                <a href="{{ url_reports }}">Список проваджень</a>
            </li>
            <li>
                <a href="{{ url_participants }}">Учасники проваджень</a>
            </li>
            <li>
                <a href="{{ url_subjects }}">Об'єкти проваджень</a>
            </li>
        </ul>
    </div>
</nav>
{% endblock sidebar %}

{% block title %}
<div class="col">
    <span class="h1">Список проваджень</span>
    <a class="btn btn-outline-info modal-button"
        id="add-report" href="{% url 'freports:add_new_report' %}">Додати провадження</a>
</div>
{% endblock title %}

templates/ang/login-detail.html
<div class="row justify-content-md-center">
    <div class="col-6">
        <h1>Login</h1>
        <form ng-submit="doLogin(user)">
            <div class="form-group">
                <label for="inputLogin">Username</label>
                <input type="text" class="form-control" id="inputLogin" placeholder="Login" ng-model="user.username">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" ng-model="user.password">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
        </form>
    </div>
</div>

templates/ang/nav-bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" ng-href="/angular">ForensicManager <span class="badge badge-info badge-pill">Beta</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" 
        aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link"
                        href="#">Провадження</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                        href="#">Контакти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                        href="#">Суди</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                        href="#">Завдання</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                        href="#">Фінанси</a>
                </li>
            </ul>
            <a class="btn btn-warning mr-3" href="http://127.0.0.1:8000/freports/">Exit Beta</a>
            <div class="btn-group" role="group">
                <button type="button" class="btn" aria-haspopup="true" aria-expanded="false">
                    Trivvet
                </button>
                <button type="button" class="btn dropdown-toggle dropdown-toggle-split"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </button>
                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                    <a class="dropdown-item" href="#">Оновлення даних</a>
                    <a class="dropdown-item" href="#">Записи логування</a>
                    <a class="dropdown-item" ng-href="/angular/logout">Вийти</a>
                </div>
            </div>
        </div>
    </div>
 <!-- Navbar content -->
</nav>

templates/ang/pagination.html
<nav aria-label="Page navigation" ng-hide="pages.length < 2">
    <ul class="pagination">
        <li class="page-item" ng-class="{ disabled : pagination.current == 1 }">
            <a class="page-link" href="#" ng-click="setCurrent(pagination.current - 1)" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
            <li class="page-item" ng-class="{ active : pageNumber == pagination.current }" ng-repeat="pageNumber in pages track by tracker(pageNumber, $index)">
                <a class="page-link" href="#" ng-click="setCurrent(pageNumber)">
                    {{ pageNumber }}
                </a>
            </li>
        <li class="page-item" ng-class="{ disabled : pagination.current == pagination.last }">
            <a class="page-link" href="#" ng-click="setCurrent(pagination.current + 1)" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
    
</nav>

templates/ang/side-bar.html
<nav id="sidebar" ng-model="bar">
    <div>
        <div class="sidebar-header">
            <h2 class="text-center">Провадження</h2>
        </div>

        <ul class="list-unstyled components">
            <li class="active">
                <a href="#">Список проваджень</a>
            </li>
            <li>
                <a href="#">Учасники проваджень</a>
            </li>
            <li>
                <a href="#">Об'єкти проваджень</a>
            </li>
        </ul>
    </div>
</nav>